### ISSUE TITLE
Trying to run fings in Cromwell.

### ISSUE THREAD

**Issue by njbernstein** [cpwardell/FiNGS#3]
Hi there,

I'm trying Fings out in a cromwell pipeline. 

The container seems to get built fine, but the fings command fails for the following reason.

```
[UserAction] Unexpected exit status 2 while running "/bin/bash /cromwell_root/script": python: can't open file '/opt/conda/lib/python3.7/site-packages/fings/FiNGS.py': [Errno 2] No such file or directory
```

The command I run in the container is 
```
fings -t test.bam -v test-filtered.vcf
````
Any thoughts?

**Comment by njbernstein** [comment]
Looks like the entrypoint for the docket container is wrong. `'/opt/conda/lib/python3.7/site-packages/fings/FiNGS.py'` doesnt run even when I build it from scratch

**Comment by njbernstein** [comment]
The path now needs to be: /opt/conda/lib/python3.8/site-packages/fings/FiNGS.py

**Comment by njbernstein** [comment]
You should have the FiNGS.py be able to be accessed just with `fings` command by using entrypoints in your setup.py. That way you'll avoid hardcoding a path like above.

**Comment by cpwardell** [comment]
Thanks for the tip; I added a fings command to the entrypoint.
